keys:
  - &user_george age1lgmlzm9asevnq45z7zwsmzddz7qmjwhuvr0mhceftkkffgrjyvcsng9t3p
  - &host_gs_thinkpad_t480s age194ysktmvcyfrxl4etdq2al76q3vll405z0plc8vk4up47fwzr52q00ratx
  - &host_gs_pi4 age1zjpq985pnns0cdrc03plwh8zl3nn7u5czcnfxpl7cnrsa7ascv9ql0f2f8
  # - &host_gs_server <derive with: ssh-to-age -i /etc/ssh/ssh_host_ed25519_key.pub>

creation_rules:
  - path_regex: secrets/gs-pi4\.yaml$
    key_groups:
      - age:
          - *user_george
          - *host_gs_pi4
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *user_george
          - *host_gs_thinkpad_t480s
